# Generated by Django 2.2.3 on 2019-07-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('about', models.TextField()),
            ],
        ),
    ]
