# Generated by Django 2.2.3 on 2019-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0004_profilemodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='aver',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
