# Generated by Django 2.2.3 on 2019-07-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='aver',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
